:imagesdir: images
:includedir: common
:specificdir: specific
:generateddir: generated
:icons: font
:toc2: left
:toc-title: Quick Start Reference Deployment
:toclevels: 2
:template_services_ec2:
include::{specificdir}/_settings.adoc[]

[.text-center]
== _{partner-product-name}_ on the AWS Cloud
[.text-left]
include::{includedir}/introduction.adoc[]

== Overview
include::{includedir}/overview.adoc[]


== _{partner-product-name}_ on AWS
ifndef::in_repo[_**This portion of the deployment guide is located at `docs/{specificdir}/product_description.adoc`**_]
include::{specificdir}/product_description.adoc[]

== Cost
include::{includedir}/cost.adoc[]

== Software Licenses
ifndef::in_repo[_**This portion of the deployment guide is located at `docs/{specificdir}/licenses.adoc`**_]
include::{specificdir}/licenses.adoc[]

== Architecture
ifndef::in_repo[_**This portion of the deployment guide is located at `docs/{specificdir}/architecture.adoc`**_]

include::{specificdir}/architecture.adoc[]

== Planning the deployment

=== Specialized knowledge
include::{includedir}/planning_deployment.adoc[]

== Deployment Steps

Follow the step-by-step instructions in this section to build the
virtual network environment illustrated in architecture section i
your AWS account. The AWS CloudFormation template provided with this
Quick Start bootstraps the AWS networking infrastructure on the AWS
Cloud from scratch.

=== Step 1 Prepare An AWS Account

include::{includedir}/prepare_an_aws_ccount.adoc[]

=== Step 2 Launch the stack
include::{includedir}/launch_the_stack.adoc[]

== Parameters
include::{generateddir}/parameters/index.adoc[]

== Troubleshooting
ifndef::in_repo[_**This portion of the deployment guide is located at `docs/{specificdir}/troubleshooting.adoc`**_]

include::{specificdir}/troubleshooting.adoc[]

== Security
ifndef::in_repo[_**This portion of the deployment guide is located at `docs/{specificdir}/security.adoc`**_]

include::{specificdir}/security.adoc[]


== Quick Start reference deployments

* AWS Quick Start home page +
https://aws.amazon.com/quickstart/

== GitHub Repository

You can visit our https://github.com/aws-quickstart/{quickstart-project-name}[GitHub repository] to download
the templates and scripts for this Quick Start, to post your comments,
and to share your customizations with others.
